### 1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [16]:
import numpy as np
arr = np.zeros(64).reshape(8, 8)

for i in range(8):
    for j in range(8):
        if i % 2 == 0:
            if j % 2 == 0:
                arr[i][j] = 1
        else:
            if j % 2 != 0:
                arr[i][j] = 1
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


### 1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [2]:
arr = np.empty((0, 0))
for _ in range(5):
    arr = np.append(arr, np.arange(0, 5))
arr = arr.reshape(5, 5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.

In [18]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.66348723 0.82348132 0.05621538]
  [0.9033024  0.97248343 0.04866666]
  [0.60158085 0.91172162 0.18090027]]

 [[0.1817808  0.15156952 0.25857972]
  [0.89560126 0.25702668 0.2409899 ]
  [0.93075782 0.93581532 0.54992397]]

 [[0.51121246 0.93473827 0.81649201]
  [0.75765934 0.71471415 0.6248974 ]
  [0.94225998 0.77350615 0.87960052]]]


### 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах

In [4]:
arr = np.ones(10)
j = np.array
arr = np.append(arr, np.zeros(10))
arr = np.append(arr, np.ones(10))
arr = np.reshape(arr, (3, 10))

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [5]:
arr = np.random.random((10))
arr = np.sort(arr)[::-1]
print(arr)

[0.87415916 0.86909906 0.83532415 0.74385745 0.59493774 0.46069207
 0.42926477 0.41383864 0.38915096 0.32919664]


### 1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.


In [6]:
import random as r
arr = np.random.random((r.randint(1, 10), r.randint(1, 10)))
print(np.shape(arr), np.size(arr), np.ndim(arr))

(3, 2) 6 2


### Задание 2.3.1
Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.


In [19]:
import pandas as pd

a = pd.Series([40, 50])
b = pd.Series([10, 40])

Evk = ((b[0] - a[0])**2 + (b[1] - a[1]) ** 2)**0.5
print(Evk)

31.622776601683793


### Задание 2.3.2
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных


In [2]:
import pandas as pd
frame = pd.read_csv('ames.csv')
frame

Order        PID  MS.SubClass MS.Zoning  Lot.Frontage  Lot.Area Street  \
0         1  526301100           20        RL         141.0     31770   Pave   
1         2  526350040           20        RH          80.0     11622   Pave   
2         3  526351010           20        RL          81.0     14267   Pave   
3         4  526353030           20        RL          93.0     11160   Pave   
4         5  527105010           60        RL          74.0     13830   Pave   
...     ...        ...          ...       ...           ...       ...    ...   
2925   2926  923275080           80        RL          37.0      7937   Pave   
2926   2927  923276100           20        RL           NaN      8885   Pave   
2927   2928  923400125           85        RL          62.0     10441   Pave   
2928   2929  924100070           20        RL          77.0     10010   Pave   
2929   2930  924151050           60        RL          74.0      9627   Pave   

     Alley Lot.Shape Land.Contour  ... Pool.Area Pool.QC  Fence Misc.Feature  \
0      NaN       IR1          Lvl  ...         0     NaN    NaN          NaN   
1      NaN       Reg          Lvl  ...         0     NaN  MnPrv          NaN   
2      NaN       IR1          Lvl  ...         0     NaN    NaN         Gar2   
3      NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   
4      NaN       IR1          Lvl  ...         0     NaN  MnPrv          NaN   
...    ...       ...          ...  ...       ...     ...    ...          ...   
2925   NaN       IR1          Lvl  ...         0     NaN  GdPrv          NaN   
2926   NaN       IR1          Low  ...         0     NaN  MnPrv          NaN   
2927   NaN       Reg          Lvl  ...         0     NaN  MnPrv         Shed   
2928   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   
2929   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   

     Misc.Val Mo.Sold Yr.Sold Sale.Type  Sale.Condition  SalePrice  
0           0       5    2010       WD           Normal     215000  
1           0       6    2010       WD           Normal     105000  
2       12500       6    2010       WD           Normal     172000  
3           0       4    2010       WD           Normal     244000  
4           0       3    2010       WD           Normal     189900  
...       ...     ...     ...       ...             ...        ...  
2925        0       3    2006       WD           Normal     142500  
2926        0       6    2006       WD           Normal     131000  
2927      700       7    2006       WD           Normal     132000  
2928        0       4    2006       WD           Normal     170000  
2929        0      11    2006       WD           Normal     188000  

[2930 rows x 82 columns]

### Задание 2.3.3
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [3]:
frame.head(2)

Order        PID  MS.SubClass MS.Zoning  Lot.Frontage  Lot.Area Street  \
0      1  526301100           20        RL         141.0     31770   Pave   
1      2  526350040           20        RH          80.0     11622   Pave   

  Alley Lot.Shape Land.Contour  ... Pool.Area Pool.QC  Fence Misc.Feature  \
0   NaN       IR1          Lvl  ...         0     NaN    NaN          NaN   
1   NaN       Reg          Lvl  ...         0     NaN  MnPrv          NaN   

  Misc.Val Mo.Sold Yr.Sold Sale.Type  Sale.Condition  SalePrice  
0        0       5    2010       WD           Normal     215000  
1        0       6    2010       WD           Normal     105000  

[2 rows x 82 columns]

In [4]:
frame.tail(3)

Order        PID  MS.SubClass MS.Zoning  Lot.Frontage  Lot.Area Street  \
2927   2928  923400125           85        RL          62.0     10441   Pave   
2928   2929  924100070           20        RL          77.0     10010   Pave   
2929   2930  924151050           60        RL          74.0      9627   Pave   

     Alley Lot.Shape Land.Contour  ... Pool.Area Pool.QC  Fence Misc.Feature  \
2927   NaN       Reg          Lvl  ...         0     NaN  MnPrv         Shed   
2928   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   
2929   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   

     Misc.Val Mo.Sold Yr.Sold Sale.Type  Sale.Condition  SalePrice  
2927      700       7    2006       WD           Normal     132000  
2928        0       4    2006       WD           Normal     170000  
2929        0      11    2006       WD           Normal     188000  

[3 rows x 82 columns]

In [5]:
frame.shape

(2930, 82)

In [6]:
frame.describe()

Order           PID  MS.SubClass  Lot.Frontage       Lot.Area  \
count  2930.00000  2.930000e+03  2930.000000   2440.000000    2930.000000   
mean   1465.50000  7.144645e+08    57.387372     69.224590   10147.921843   
std     845.96247  1.887308e+08    42.638025     23.365335    7880.017759   
min       1.00000  5.263011e+08    20.000000     21.000000    1300.000000   
25%     733.25000  5.284770e+08    20.000000     58.000000    7440.250000   
50%    1465.50000  5.354536e+08    50.000000     68.000000    9436.500000   
75%    2197.75000  9.071811e+08    70.000000     80.000000   11555.250000   
max    2930.00000  1.007100e+09   190.000000    313.000000  215245.000000   

       Overall.Qual  Overall.Cond   Year.Built  Year.Remod.Add  Mas.Vnr.Area  \
count   2930.000000   2930.000000  2930.000000     2930.000000   2907.000000   
mean       6.094881      5.563140  1971.356314     1984.266553    101.896801   
std        1.411026      1.111537    30.245361       20.860286    179.112611   
min        1.000000      1.000000  1872.000000     1950.000000      0.000000   
25%        5.000000      5.000000  1954.000000     1965.000000      0.000000   
50%        6.000000      5.000000  1973.000000     1993.000000      0.000000   
75%        7.000000      6.000000  2001.000000     2004.000000    164.000000   
max       10.000000      9.000000  2010.000000     2010.000000   1600.000000   

       ...  Wood.Deck.SF  Open.Porch.SF  Enclosed.Porch  X3Ssn.Porch  \
count  ...   2930.000000    2930.000000     2930.000000  2930.000000   
mean   ...     93.751877      47.533447       23.011604     2.592491   
std    ...    126.361562      67.483400       64.139059    25.141331   
min    ...      0.000000       0.000000        0.000000     0.000000   
25%    ...      0.000000       0.000000        0.000000     0.000000   
50%    ...      0.000000      27.000000        0.000000     0.000000   
75%    ...    168.000000      70.000000        0.000000     0.000000   
max    ...   1424.000000     742.000000     1012.000000   508.000000   

       Screen.Porch    Pool.Area      Misc.Val      Mo.Sold      Yr.Sold  \
count   2930.000000  2930.000000   2930.000000  2930.000000  2930.000000   
mean      16.002048     2.243345     50.635154     6.216041  2007.790444   
std       56.087370    35.597181    566.344288     2.714492     1.316613   
min        0.000000     0.000000      0.000000     1.000000  2006.000000   
25%        0.000000     0.000000      0.000000     4.000000  2007.000000   
50%        0.000000     0.000000      0.000000     6.000000  2008.000000   
75%        0.000000     0.000000      0.000000     8.000000  2009.000000   
max      576.000000   800.000000  17000.000000    12.000000  2010.000000   

           SalePrice  
count    2930.000000  
mean   180796.060068  
std     79886.692357  
min     12789.000000  
25%    129500.000000  
50%    160000.000000  
75%    213500.000000  
max    755000.000000  

[8 rows x 39 columns]

In [7]:
frame.loc[1:4]

Order        PID  MS.SubClass MS.Zoning  Lot.Frontage  Lot.Area Street  \
1      2  526350040           20        RH          80.0     11622   Pave   
2      3  526351010           20        RL          81.0     14267   Pave   
3      4  526353030           20        RL          93.0     11160   Pave   
4      5  527105010           60        RL          74.0     13830   Pave   

  Alley Lot.Shape Land.Contour  ... Pool.Area Pool.QC  Fence Misc.Feature  \
1   NaN       Reg          Lvl  ...         0     NaN  MnPrv          NaN   
2   NaN       IR1          Lvl  ...         0     NaN    NaN         Gar2   
3   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   
4   NaN       IR1          Lvl  ...         0     NaN  MnPrv          NaN   

  Misc.Val Mo.Sold Yr.Sold Sale.Type  Sale.Condition  SalePrice  
1        0       6    2010       WD           Normal     105000  
2    12500       6    2010       WD           Normal     172000  
3        0       4    2010       WD           Normal     244000  
4        0       3    2010       WD           Normal     189900  

[4 rows x 82 columns]

In [8]:
frame.iloc[1:4]

Order        PID  MS.SubClass MS.Zoning  Lot.Frontage  Lot.Area Street  \
1      2  526350040           20        RH          80.0     11622   Pave   
2      3  526351010           20        RL          81.0     14267   Pave   
3      4  526353030           20        RL          93.0     11160   Pave   

  Alley Lot.Shape Land.Contour  ... Pool.Area Pool.QC  Fence Misc.Feature  \
1   NaN       Reg          Lvl  ...         0     NaN  MnPrv          NaN   
2   NaN       IR1          Lvl  ...         0     NaN    NaN         Gar2   
3   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   

  Misc.Val Mo.Sold Yr.Sold Sale.Type  Sale.Condition  SalePrice  
1        0       6    2010       WD           Normal     105000  
2    12500       6    2010       WD           Normal     172000  
3        0       4    2010       WD           Normal     244000  

[3 rows x 82 columns]

In [10]:
new_frame = frame[frame['Lot.Frontage'] >= 100]
new_frame

Order        PID  MS.SubClass MS.Zoning  Lot.Frontage  Lot.Area Street  \
0         1  526301100           20        RL         141.0     31770   Pave   
16       17  527225035           50        RL         152.0     12134   Pave   
18       19  527276150           20        RL         140.0     19138   Pave   
20       21  527358140           20        RL         105.0     11751   Pave   
36       37  528108120           60        RL         102.0     12858   Pave   
...     ...        ...          ...       ...           ...       ...    ...   
2804   2805  907290260           60        RL         120.0     15611   Pave   
2817   2818  908102320           20        RL         134.0     17755   Pave   
2889   2890  914476130           80        RL         140.0     11080   Pave   
2903   2904  923125030           20   A (agr)         125.0     31250   Pave   
2924   2925  923251180           20        RL         160.0     20000   Pave   

     Alley Lot.Shape Land.Contour  ... Pool.Area Pool.QC  Fence Misc.Feature  \
0      NaN       IR1          Lvl  ...         0     NaN    NaN          NaN   
16     NaN       IR1          Bnk  ...         0     NaN    NaN          NaN   
18     NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   
20     NaN       IR1          Lvl  ...         0     NaN  MnPrv          NaN   
36     NaN       IR1          Lvl  ...         0     NaN    NaN          NaN   
...    ...       ...          ...  ...       ...     ...    ...          ...   
2804   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   
2817   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   
2889   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   
2903   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   
2924   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN   

     Misc.Val Mo.Sold Yr.Sold Sale.Type  Sale.Condition  SalePrice  
0           0       5    2010       WD           Normal     215000  
16          0       6    2010       WD           Normal     164000  
18          0       6    2010       WD           Normal     141000  
20          0       1    2010       COD          Normal     190000  
36          0       1    2010       New         Partial     376162  
...       ...     ...     ...       ...             ...        ...  
2804        0       7    2006       New         Partial     233230  
2817        0      11    2006       WD           Normal     149900  
2889        0       5    2006       WD           Normal     148000  
2903        0       5    2006       WD           Normal      81500  
2924        0       9    2006       WD          Abnorml     131000  

[199 rows x 82 columns]

### Задание 3.2.2
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [8]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
df = pd.read_csv('raw.csv')

length = list(df['sepal_length_cm'])
length = list(map(lambda x: [x], length))
length = np.array(length)

minmax = preprocessing.MinMaxScaler(feature_range = (0, 1))
minmax = minmax.fit_transform(length)
minmax

array([[0.22222222],
       [0.16666667],
       [0.11111111],
       [0.08333333],
       [0.19444444],
       [0.30555556],
       [0.08333333],
       [0.19444444],
       [0.02777778],
       [0.16666667],
       [0.30555556],
       [0.13888889],
       [0.13888889],
       [0.        ],
       [0.41666667],
       [0.38888889],
       [0.30555556],
       [0.22222222],
       [0.38888889],
       [0.22222222],
       [0.30555556],
       [0.22222222],
       [0.08333333],
       [0.22222222],
       [0.13888889],
       [0.19444444],
       [0.19444444],
       [0.25      ],
       [0.25      ],
       [0.11111111],
       [0.13888889],
       [0.30555556],
       [0.25      ],
       [0.33333333],
       [0.16666667],
       [0.19444444],
       [0.33333333],
       [0.16666667],
       [0.02777778],
       [0.22222222],
       [0.19444444],
       [0.05555556],
       [0.02777778],
       [0.19444444],
       [0.22222222],
       [0.13888889],
       [0.22222222],
       [0.083

In [11]:
width = list(df['sepal_width_cm'])
width = list(map(lambda x: [x], width))
width = np.array(width)

scaler = preprocessing.StandardScaler()
standard = scaler.fit_transform(width)
standard

array([[ 1.03205722],
       [-0.1249576 ],
       [ 0.33784833],
       [ 0.10644536],
       [ 1.26346019],
       [ 1.95766909],
       [ 0.80065426],
       [ 0.80065426],
       [-0.35636057],
       [ 0.10644536],
       [ 1.49486315],
       [ 0.80065426],
       [-0.1249576 ],
       [-0.1249576 ],
       [ 2.18907205],
       [ 3.11468391],
       [ 1.95766909],
       [ 1.03205722],
       [ 1.72626612],
       [ 1.72626612],
       [ 0.80065426],
       [ 1.49486315],
       [ 1.26346019],
       [ 0.56925129],
       [ 0.80065426],
       [-0.1249576 ],
       [ 0.80065426],
       [ 1.03205722],
       [ 0.80065426],
       [ 0.33784833],
       [ 0.10644536],
       [ 0.80065426],
       [ 2.42047502],
       [ 2.65187798],
       [ 0.10644536],
       [ 0.33784833],
       [ 1.03205722],
       [ 0.10644536],
       [-0.1249576 ],
       [ 0.80065426],
       [ 1.03205722],
       [-1.74477836],
       [ 0.33784833],
       [ 1.03205722],
       [ 1.72626612],
       [-0